// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gate_game.proto

#ifndef PROTOBUF_msg_5fgate_5fgame_2eproto__INCLUDED
#define PROTOBUF_msg_5fgate_5fgame_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "msg_gate_login.pb.h"
// @@protoc_insertion_point(includes)

namespace msgs2s {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto();
void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto();

class MsgGT2GSAddUser;
class MsgGT2GSRemoveUser;
class MsgGT2GSOfflineUser;
class MsgGS2GTOnlines;

// ===================================================================

class MsgGT2GSAddUser : public ::google::protobuf::Message {
 public:
  MsgGT2GSAddUser();
  virtual ~MsgGT2GSAddUser();

  MsgGT2GSAddUser(const MsgGT2GSAddUser& from);

  inline MsgGT2GSAddUser& operator=(const MsgGT2GSAddUser& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGT2GSAddUser& default_instance();

  void Swap(MsgGT2GSAddUser* other);

  // implements Message ----------------------------------------------

  MsgGT2GSAddUser* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGT2GSAddUser& from);
  void MergeFrom(const MsgGT2GSAddUser& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .msgs2s.GTLGData data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::msgs2s::GTLGData& data() const;
  inline ::msgs2s::GTLGData* mutable_data();
  inline ::msgs2s::GTLGData* release_data();
  inline void set_allocated_data(::msgs2s::GTLGData* data);

  // @@protoc_insertion_point(class_scope:msgs2s.MsgGT2GSAddUser)
 private:
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::msgs2s::GTLGData* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto();

  void InitAsDefaultInstance();
  static MsgGT2GSAddUser* default_instance_;
};
// -------------------------------------------------------------------

class MsgGT2GSRemoveUser : public ::google::protobuf::Message {
 public:
  MsgGT2GSRemoveUser();
  virtual ~MsgGT2GSRemoveUser();

  MsgGT2GSRemoveUser(const MsgGT2GSRemoveUser& from);

  inline MsgGT2GSRemoveUser& operator=(const MsgGT2GSRemoveUser& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGT2GSRemoveUser& default_instance();

  void Swap(MsgGT2GSRemoveUser* other);

  // implements Message ----------------------------------------------

  MsgGT2GSRemoveUser* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGT2GSRemoveUser& from);
  void MergeFrom(const MsgGT2GSRemoveUser& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 trans = 1;
  inline bool has_trans() const;
  inline void clear_trans();
  static const int kTransFieldNumber = 1;
  inline ::google::protobuf::uint32 trans() const;
  inline void set_trans(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:msgs2s.MsgGT2GSRemoveUser)
 private:
  inline void set_has_trans();
  inline void clear_has_trans();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 trans_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto();

  void InitAsDefaultInstance();
  static MsgGT2GSRemoveUser* default_instance_;
};
// -------------------------------------------------------------------

class MsgGT2GSOfflineUser : public ::google::protobuf::Message {
 public:
  MsgGT2GSOfflineUser();
  virtual ~MsgGT2GSOfflineUser();

  MsgGT2GSOfflineUser(const MsgGT2GSOfflineUser& from);

  inline MsgGT2GSOfflineUser& operator=(const MsgGT2GSOfflineUser& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGT2GSOfflineUser& default_instance();

  void Swap(MsgGT2GSOfflineUser* other);

  // implements Message ----------------------------------------------

  MsgGT2GSOfflineUser* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGT2GSOfflineUser& from);
  void MergeFrom(const MsgGT2GSOfflineUser& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 trans = 1;
  inline bool has_trans() const;
  inline void clear_trans();
  static const int kTransFieldNumber = 1;
  inline ::google::protobuf::uint32 trans() const;
  inline void set_trans(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:msgs2s.MsgGT2GSOfflineUser)
 private:
  inline void set_has_trans();
  inline void clear_has_trans();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 trans_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto();

  void InitAsDefaultInstance();
  static MsgGT2GSOfflineUser* default_instance_;
};
// -------------------------------------------------------------------

class MsgGS2GTOnlines : public ::google::protobuf::Message {
 public:
  MsgGS2GTOnlines();
  virtual ~MsgGS2GTOnlines();

  MsgGS2GTOnlines(const MsgGS2GTOnlines& from);

  inline MsgGS2GTOnlines& operator=(const MsgGS2GTOnlines& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGS2GTOnlines& default_instance();

  void Swap(MsgGS2GTOnlines* other);

  // implements Message ----------------------------------------------

  MsgGS2GTOnlines* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGS2GTOnlines& from);
  void MergeFrom(const MsgGS2GTOnlines& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 onlines = 1;
  inline bool has_onlines() const;
  inline void clear_onlines();
  static const int kOnlinesFieldNumber = 1;
  inline ::google::protobuf::uint32 onlines() const;
  inline void set_onlines(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:msgs2s.MsgGS2GTOnlines)
 private:
  inline void set_has_onlines();
  inline void clear_has_onlines();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 onlines_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto();
  friend void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto();

  void InitAsDefaultInstance();
  static MsgGS2GTOnlines* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgGT2GSAddUser

// required .msgs2s.GTLGData data = 1;
inline bool MsgGT2GSAddUser::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGT2GSAddUser::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGT2GSAddUser::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGT2GSAddUser::clear_data() {
  if (data_ != NULL) data_->::msgs2s::GTLGData::Clear();
  clear_has_data();
}
inline const ::msgs2s::GTLGData& MsgGT2GSAddUser::data() const {
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
inline ::msgs2s::GTLGData* MsgGT2GSAddUser::mutable_data() {
  set_has_data();
  if (data_ == NULL) data_ = new ::msgs2s::GTLGData;
  return data_;
}
inline ::msgs2s::GTLGData* MsgGT2GSAddUser::release_data() {
  clear_has_data();
  ::msgs2s::GTLGData* temp = data_;
  data_ = NULL;
  return temp;
}
inline void MsgGT2GSAddUser::set_allocated_data(::msgs2s::GTLGData* data) {
  delete data_;
  data_ = data;
  if (data) {
    set_has_data();
  } else {
    clear_has_data();
  }
}

// -------------------------------------------------------------------

// MsgGT2GSRemoveUser

// required uint32 trans = 1;
inline bool MsgGT2GSRemoveUser::has_trans() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGT2GSRemoveUser::set_has_trans() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGT2GSRemoveUser::clear_has_trans() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGT2GSRemoveUser::clear_trans() {
  trans_ = 0u;
  clear_has_trans();
}
inline ::google::protobuf::uint32 MsgGT2GSRemoveUser::trans() const {
  return trans_;
}
inline void MsgGT2GSRemoveUser::set_trans(::google::protobuf::uint32 value) {
  set_has_trans();
  trans_ = value;
}

// -------------------------------------------------------------------

// MsgGT2GSOfflineUser

// required uint32 trans = 1;
inline bool MsgGT2GSOfflineUser::has_trans() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGT2GSOfflineUser::set_has_trans() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGT2GSOfflineUser::clear_has_trans() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGT2GSOfflineUser::clear_trans() {
  trans_ = 0u;
  clear_has_trans();
}
inline ::google::protobuf::uint32 MsgGT2GSOfflineUser::trans() const {
  return trans_;
}
inline void MsgGT2GSOfflineUser::set_trans(::google::protobuf::uint32 value) {
  set_has_trans();
  trans_ = value;
}

// -------------------------------------------------------------------

// MsgGS2GTOnlines

// required uint32 onlines = 1;
inline bool MsgGS2GTOnlines::has_onlines() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGS2GTOnlines::set_has_onlines() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGS2GTOnlines::clear_has_onlines() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGS2GTOnlines::clear_onlines() {
  onlines_ = 0u;
  clear_has_onlines();
}
inline ::google::protobuf::uint32 MsgGS2GTOnlines::onlines() const {
  return onlines_;
}
inline void MsgGS2GTOnlines::set_onlines(::google::protobuf::uint32 value) {
  set_has_onlines();
  onlines_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs2s

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fgate_5fgame_2eproto__INCLUDED
