// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booth.proto

#ifndef PROTOBUF_booth_2eproto__INCLUDED
#define PROTOBUF_booth_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace clientmsg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_booth_2eproto();
void protobuf_AssignDesc_booth_2eproto();
void protobuf_ShutdownFile_booth_2eproto();

class HoldBooth;
class BoothState;
class LeaveBooth;
class GetBoothState;

// ===================================================================

class HoldBooth : public ::google::protobuf::Message {
 public:
  HoldBooth();
  virtual ~HoldBooth();

  HoldBooth(const HoldBooth& from);

  inline HoldBooth& operator=(const HoldBooth& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HoldBooth& default_instance();

  void Swap(HoldBooth* other);

  // implements Message ----------------------------------------------

  HoldBooth* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HoldBooth& from);
  void MergeFrom(const HoldBooth& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 cityid = 1;
  inline bool has_cityid() const;
  inline void clear_cityid();
  static const int kCityidFieldNumber = 1;
  inline ::google::protobuf::uint32 cityid() const;
  inline void set_cityid(::google::protobuf::uint32 value);

  // optional uint32 boothid = 2;
  inline bool has_boothid() const;
  inline void clear_boothid();
  static const int kBoothidFieldNumber = 2;
  inline ::google::protobuf::uint32 boothid() const;
  inline void set_boothid(::google::protobuf::uint32 value);

  // optional uint32 charid = 3;
  inline bool has_charid() const;
  inline void clear_charid();
  static const int kCharidFieldNumber = 3;
  inline ::google::protobuf::uint32 charid() const;
  inline void set_charid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:clientmsg.HoldBooth)
 private:
  inline void set_has_cityid();
  inline void clear_has_cityid();
  inline void set_has_boothid();
  inline void clear_has_boothid();
  inline void set_has_charid();
  inline void clear_has_charid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 cityid_;
  ::google::protobuf::uint32 boothid_;
  ::google::protobuf::uint32 charid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static HoldBooth* default_instance_;
};
// -------------------------------------------------------------------

class BoothState : public ::google::protobuf::Message {
 public:
  BoothState();
  virtual ~BoothState();

  BoothState(const BoothState& from);

  inline BoothState& operator=(const BoothState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BoothState& default_instance();

  void Swap(BoothState* other);

  // implements Message ----------------------------------------------

  BoothState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BoothState& from);
  void MergeFrom(const BoothState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .clientmsg.HoldBooth states = 1;
  inline int states_size() const;
  inline void clear_states();
  static const int kStatesFieldNumber = 1;
  inline const ::clientmsg::HoldBooth& states(int index) const;
  inline ::clientmsg::HoldBooth* mutable_states(int index);
  inline ::clientmsg::HoldBooth* add_states();
  inline const ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >&
      states() const;
  inline ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >*
      mutable_states();

  // @@protoc_insertion_point(class_scope:clientmsg.BoothState)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth > states_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static BoothState* default_instance_;
};
// -------------------------------------------------------------------

class LeaveBooth : public ::google::protobuf::Message {
 public:
  LeaveBooth();
  virtual ~LeaveBooth();

  LeaveBooth(const LeaveBooth& from);

  inline LeaveBooth& operator=(const LeaveBooth& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveBooth& default_instance();

  void Swap(LeaveBooth* other);

  // implements Message ----------------------------------------------

  LeaveBooth* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LeaveBooth& from);
  void MergeFrom(const LeaveBooth& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 boothids = 1;
  inline int boothids_size() const;
  inline void clear_boothids();
  static const int kBoothidsFieldNumber = 1;
  inline ::google::protobuf::uint32 boothids(int index) const;
  inline void set_boothids(int index, ::google::protobuf::uint32 value);
  inline void add_boothids(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      boothids() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_boothids();

  // @@protoc_insertion_point(class_scope:clientmsg.LeaveBooth)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > boothids_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static LeaveBooth* default_instance_;
};
// -------------------------------------------------------------------

class GetBoothState : public ::google::protobuf::Message {
 public:
  GetBoothState();
  virtual ~GetBoothState();

  GetBoothState(const GetBoothState& from);

  inline GetBoothState& operator=(const GetBoothState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetBoothState& default_instance();

  void Swap(GetBoothState* other);

  // implements Message ----------------------------------------------

  GetBoothState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetBoothState& from);
  void MergeFrom(const GetBoothState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:clientmsg.GetBoothState)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_booth_2eproto();
  friend void protobuf_AssignDesc_booth_2eproto();
  friend void protobuf_ShutdownFile_booth_2eproto();

  void InitAsDefaultInstance();
  static GetBoothState* default_instance_;
};
// ===================================================================


// ===================================================================

// HoldBooth

// optional uint32 cityid = 1;
inline bool HoldBooth::has_cityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HoldBooth::set_has_cityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HoldBooth::clear_has_cityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HoldBooth::clear_cityid() {
  cityid_ = 0u;
  clear_has_cityid();
}
inline ::google::protobuf::uint32 HoldBooth::cityid() const {
  return cityid_;
}
inline void HoldBooth::set_cityid(::google::protobuf::uint32 value) {
  set_has_cityid();
  cityid_ = value;
}

// optional uint32 boothid = 2;
inline bool HoldBooth::has_boothid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HoldBooth::set_has_boothid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HoldBooth::clear_has_boothid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HoldBooth::clear_boothid() {
  boothid_ = 0u;
  clear_has_boothid();
}
inline ::google::protobuf::uint32 HoldBooth::boothid() const {
  return boothid_;
}
inline void HoldBooth::set_boothid(::google::protobuf::uint32 value) {
  set_has_boothid();
  boothid_ = value;
}

// optional uint32 charid = 3;
inline bool HoldBooth::has_charid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HoldBooth::set_has_charid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HoldBooth::clear_has_charid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HoldBooth::clear_charid() {
  charid_ = 0u;
  clear_has_charid();
}
inline ::google::protobuf::uint32 HoldBooth::charid() const {
  return charid_;
}
inline void HoldBooth::set_charid(::google::protobuf::uint32 value) {
  set_has_charid();
  charid_ = value;
}

// -------------------------------------------------------------------

// BoothState

// repeated .clientmsg.HoldBooth states = 1;
inline int BoothState::states_size() const {
  return states_.size();
}
inline void BoothState::clear_states() {
  states_.Clear();
}
inline const ::clientmsg::HoldBooth& BoothState::states(int index) const {
  return states_.Get(index);
}
inline ::clientmsg::HoldBooth* BoothState::mutable_states(int index) {
  return states_.Mutable(index);
}
inline ::clientmsg::HoldBooth* BoothState::add_states() {
  return states_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >&
BoothState::states() const {
  return states_;
}
inline ::google::protobuf::RepeatedPtrField< ::clientmsg::HoldBooth >*
BoothState::mutable_states() {
  return &states_;
}

// -------------------------------------------------------------------

// LeaveBooth

// repeated uint32 boothids = 1;
inline int LeaveBooth::boothids_size() const {
  return boothids_.size();
}
inline void LeaveBooth::clear_boothids() {
  boothids_.Clear();
}
inline ::google::protobuf::uint32 LeaveBooth::boothids(int index) const {
  return boothids_.Get(index);
}
inline void LeaveBooth::set_boothids(int index, ::google::protobuf::uint32 value) {
  boothids_.Set(index, value);
}
inline void LeaveBooth::add_boothids(::google::protobuf::uint32 value) {
  boothids_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
LeaveBooth::boothids() const {
  return boothids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
LeaveBooth::mutable_boothids() {
  return &boothids_;
}

// -------------------------------------------------------------------

// GetBoothState


// @@protoc_insertion_point(namespace_scope)

}  // namespace clientmsg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_booth_2eproto__INCLUDED
