// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_gate_game.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_gate_game.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace msgs2s {

namespace {

const ::google::protobuf::Descriptor* MsgGT2GSAddUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSAddUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGT2GSRemoveUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSRemoveUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGT2GSOfflineUser_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGT2GSOfflineUser_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgGS2GTOnlines_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgGS2GTOnlines_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5fgate_5fgame_2eproto() {
  protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_gate_game.proto");
  GOOGLE_CHECK(file != NULL);
  MsgGT2GSAddUser_descriptor_ = file->message_type(0);
  static const int MsgGT2GSAddUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, data_),
  };
  MsgGT2GSAddUser_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgGT2GSAddUser_descriptor_,
      MsgGT2GSAddUser::default_instance_,
      MsgGT2GSAddUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSAddUser, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgGT2GSAddUser));
  MsgGT2GSRemoveUser_descriptor_ = file->message_type(1);
  static const int MsgGT2GSRemoveUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, trans_),
  };
  MsgGT2GSRemoveUser_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgGT2GSRemoveUser_descriptor_,
      MsgGT2GSRemoveUser::default_instance_,
      MsgGT2GSRemoveUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSRemoveUser, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgGT2GSRemoveUser));
  MsgGT2GSOfflineUser_descriptor_ = file->message_type(2);
  static const int MsgGT2GSOfflineUser_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, trans_),
  };
  MsgGT2GSOfflineUser_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgGT2GSOfflineUser_descriptor_,
      MsgGT2GSOfflineUser::default_instance_,
      MsgGT2GSOfflineUser_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGT2GSOfflineUser, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgGT2GSOfflineUser));
  MsgGS2GTOnlines_descriptor_ = file->message_type(3);
  static const int MsgGS2GTOnlines_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, onlines_),
  };
  MsgGS2GTOnlines_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgGS2GTOnlines_descriptor_,
      MsgGS2GTOnlines::default_instance_,
      MsgGS2GTOnlines_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgGS2GTOnlines, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgGS2GTOnlines));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5fgate_5fgame_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgGT2GSAddUser_descriptor_, &MsgGT2GSAddUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgGT2GSRemoveUser_descriptor_, &MsgGT2GSRemoveUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgGT2GSOfflineUser_descriptor_, &MsgGT2GSOfflineUser::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgGS2GTOnlines_descriptor_, &MsgGS2GTOnlines::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto() {
  delete MsgGT2GSAddUser::default_instance_;
  delete MsgGT2GSAddUser_reflection_;
  delete MsgGT2GSRemoveUser::default_instance_;
  delete MsgGT2GSRemoveUser_reflection_;
  delete MsgGT2GSOfflineUser::default_instance_;
  delete MsgGT2GSOfflineUser_reflection_;
  delete MsgGS2GTOnlines::default_instance_;
  delete MsgGS2GTOnlines_reflection_;
}

void protobuf_AddDesc_msg_5fgate_5fgame_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::msgs2s::protobuf_AddDesc_msg_5fgate_5flogin_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023msg_gate_game.proto\022\006msgs2s\032\024msg_gate_"
    "login.proto\"1\n\017MsgGT2GSAddUser\022\036\n\004data\030\001"
    " \002(\0132\020.msgs2s.GTLGData\"#\n\022MsgGT2GSRemove"
    "User\022\r\n\005trans\030\001 \002(\r\"$\n\023MsgGT2GSOfflineUs"
    "er\022\r\n\005trans\030\001 \002(\r\"\"\n\017MsgGS2GTOnlines\022\017\n\007"
    "onlines\030\001 \002(\r", 213);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_gate_game.proto", &protobuf_RegisterTypes);
  MsgGT2GSAddUser::default_instance_ = new MsgGT2GSAddUser();
  MsgGT2GSRemoveUser::default_instance_ = new MsgGT2GSRemoveUser();
  MsgGT2GSOfflineUser::default_instance_ = new MsgGT2GSOfflineUser();
  MsgGS2GTOnlines::default_instance_ = new MsgGS2GTOnlines();
  MsgGT2GSAddUser::default_instance_->InitAsDefaultInstance();
  MsgGT2GSRemoveUser::default_instance_->InitAsDefaultInstance();
  MsgGT2GSOfflineUser::default_instance_->InitAsDefaultInstance();
  MsgGS2GTOnlines::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5fgate_5fgame_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5fgate_5fgame_2eproto {
  StaticDescriptorInitializer_msg_5fgate_5fgame_2eproto() {
    protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  }
} static_descriptor_initializer_msg_5fgate_5fgame_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSAddUser::kDataFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSAddUser::MsgGT2GSAddUser()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MsgGT2GSAddUser::InitAsDefaultInstance() {
  data_ = const_cast< ::msgs2s::GTLGData*>(&::msgs2s::GTLGData::default_instance());
}

MsgGT2GSAddUser::MsgGT2GSAddUser(const MsgGT2GSAddUser& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MsgGT2GSAddUser::SharedCtor() {
  _cached_size_ = 0;
  data_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSAddUser::~MsgGT2GSAddUser() {
  SharedDtor();
}

void MsgGT2GSAddUser::SharedDtor() {
  if (this != default_instance_) {
    delete data_;
  }
}

void MsgGT2GSAddUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSAddUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSAddUser_descriptor_;
}

const MsgGT2GSAddUser& MsgGT2GSAddUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSAddUser* MsgGT2GSAddUser::default_instance_ = NULL;

MsgGT2GSAddUser* MsgGT2GSAddUser::New() const {
  return new MsgGT2GSAddUser;
}

void MsgGT2GSAddUser::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_data()) {
      if (data_ != NULL) data_->::msgs2s::GTLGData::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgGT2GSAddUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .msgs2s.GTLGData data = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MsgGT2GSAddUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .msgs2s.GTLGData data = 1;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MsgGT2GSAddUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .msgs2s.GTLGData data = 1;
  if (has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MsgGT2GSAddUser::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .msgs2s.GTLGData data = 1;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSAddUser::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgGT2GSAddUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSAddUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSAddUser::MergeFrom(const MsgGT2GSAddUser& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_data()) {
      mutable_data()->::msgs2s::GTLGData::MergeFrom(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgGT2GSAddUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSAddUser::CopyFrom(const MsgGT2GSAddUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSAddUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_data()) {
    if (!this->data().IsInitialized()) return false;
  }
  return true;
}

void MsgGT2GSAddUser::Swap(MsgGT2GSAddUser* other) {
  if (other != this) {
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgGT2GSAddUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSAddUser_descriptor_;
  metadata.reflection = MsgGT2GSAddUser_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSRemoveUser::kTransFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSRemoveUser::MsgGT2GSRemoveUser()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MsgGT2GSRemoveUser::InitAsDefaultInstance() {
}

MsgGT2GSRemoveUser::MsgGT2GSRemoveUser(const MsgGT2GSRemoveUser& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MsgGT2GSRemoveUser::SharedCtor() {
  _cached_size_ = 0;
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSRemoveUser::~MsgGT2GSRemoveUser() {
  SharedDtor();
}

void MsgGT2GSRemoveUser::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGT2GSRemoveUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSRemoveUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSRemoveUser_descriptor_;
}

const MsgGT2GSRemoveUser& MsgGT2GSRemoveUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSRemoveUser* MsgGT2GSRemoveUser::default_instance_ = NULL;

MsgGT2GSRemoveUser* MsgGT2GSRemoveUser::New() const {
  return new MsgGT2GSRemoveUser;
}

void MsgGT2GSRemoveUser::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    trans_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgGT2GSRemoveUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 trans = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trans_)));
          set_has_trans();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MsgGT2GSRemoveUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 trans = 1;
  if (has_trans()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->trans(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MsgGT2GSRemoveUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 trans = 1;
  if (has_trans()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->trans(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MsgGT2GSRemoveUser::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 trans = 1;
    if (has_trans()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->trans());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSRemoveUser::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgGT2GSRemoveUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSRemoveUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSRemoveUser::MergeFrom(const MsgGT2GSRemoveUser& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_trans()) {
      set_trans(from.trans());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgGT2GSRemoveUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSRemoveUser::CopyFrom(const MsgGT2GSRemoveUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSRemoveUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGT2GSRemoveUser::Swap(MsgGT2GSRemoveUser* other) {
  if (other != this) {
    std::swap(trans_, other->trans_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgGT2GSRemoveUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSRemoveUser_descriptor_;
  metadata.reflection = MsgGT2GSRemoveUser_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgGT2GSOfflineUser::kTransFieldNumber;
#endif  // !_MSC_VER

MsgGT2GSOfflineUser::MsgGT2GSOfflineUser()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MsgGT2GSOfflineUser::InitAsDefaultInstance() {
}

MsgGT2GSOfflineUser::MsgGT2GSOfflineUser(const MsgGT2GSOfflineUser& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MsgGT2GSOfflineUser::SharedCtor() {
  _cached_size_ = 0;
  trans_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGT2GSOfflineUser::~MsgGT2GSOfflineUser() {
  SharedDtor();
}

void MsgGT2GSOfflineUser::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGT2GSOfflineUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGT2GSOfflineUser::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGT2GSOfflineUser_descriptor_;
}

const MsgGT2GSOfflineUser& MsgGT2GSOfflineUser::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGT2GSOfflineUser* MsgGT2GSOfflineUser::default_instance_ = NULL;

MsgGT2GSOfflineUser* MsgGT2GSOfflineUser::New() const {
  return new MsgGT2GSOfflineUser;
}

void MsgGT2GSOfflineUser::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    trans_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgGT2GSOfflineUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 trans = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &trans_)));
          set_has_trans();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MsgGT2GSOfflineUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 trans = 1;
  if (has_trans()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->trans(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MsgGT2GSOfflineUser::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 trans = 1;
  if (has_trans()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->trans(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MsgGT2GSOfflineUser::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 trans = 1;
    if (has_trans()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->trans());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGT2GSOfflineUser::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgGT2GSOfflineUser* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGT2GSOfflineUser*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGT2GSOfflineUser::MergeFrom(const MsgGT2GSOfflineUser& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_trans()) {
      set_trans(from.trans());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgGT2GSOfflineUser::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGT2GSOfflineUser::CopyFrom(const MsgGT2GSOfflineUser& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGT2GSOfflineUser::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGT2GSOfflineUser::Swap(MsgGT2GSOfflineUser* other) {
  if (other != this) {
    std::swap(trans_, other->trans_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgGT2GSOfflineUser::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGT2GSOfflineUser_descriptor_;
  metadata.reflection = MsgGT2GSOfflineUser_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MsgGS2GTOnlines::kOnlinesFieldNumber;
#endif  // !_MSC_VER

MsgGS2GTOnlines::MsgGS2GTOnlines()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MsgGS2GTOnlines::InitAsDefaultInstance() {
}

MsgGS2GTOnlines::MsgGS2GTOnlines(const MsgGS2GTOnlines& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MsgGS2GTOnlines::SharedCtor() {
  _cached_size_ = 0;
  onlines_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgGS2GTOnlines::~MsgGS2GTOnlines() {
  SharedDtor();
}

void MsgGS2GTOnlines::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgGS2GTOnlines::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgGS2GTOnlines::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgGS2GTOnlines_descriptor_;
}

const MsgGS2GTOnlines& MsgGS2GTOnlines::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fgate_5fgame_2eproto();
  return *default_instance_;
}

MsgGS2GTOnlines* MsgGS2GTOnlines::default_instance_ = NULL;

MsgGS2GTOnlines* MsgGS2GTOnlines::New() const {
  return new MsgGS2GTOnlines;
}

void MsgGS2GTOnlines::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    onlines_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgGS2GTOnlines::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 onlines = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &onlines_)));
          set_has_onlines();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MsgGS2GTOnlines::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 onlines = 1;
  if (has_onlines()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->onlines(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MsgGS2GTOnlines::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 onlines = 1;
  if (has_onlines()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->onlines(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MsgGS2GTOnlines::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 onlines = 1;
    if (has_onlines()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->onlines());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgGS2GTOnlines::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgGS2GTOnlines* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgGS2GTOnlines*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgGS2GTOnlines::MergeFrom(const MsgGS2GTOnlines& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_onlines()) {
      set_onlines(from.onlines());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgGS2GTOnlines::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgGS2GTOnlines::CopyFrom(const MsgGS2GTOnlines& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgGS2GTOnlines::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MsgGS2GTOnlines::Swap(MsgGS2GTOnlines* other) {
  if (other != this) {
    std::swap(onlines_, other->onlines_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgGS2GTOnlines::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgGS2GTOnlines_descriptor_;
  metadata.reflection = MsgGS2GTOnlines_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs2s

// @@protoc_insertion_point(global_scope)
